### PR TITLE
Support submodules (modules are separated by '.')

### PR DESCRIPTION
**Pull request by Arlanthir**
As discussed in Issue #11.

### CODE REVIEW

**Comment by Arlanthir** [comment]
I updated the branch because it had conflicts with the most recent master.
Have you had a chance to analyze this yet?

Cheers

**Comment by ohager** [comment]
Any news on that PR. Will it be merged? this is in fact an interesting feature

**Comment by jerylvaz** [comment]
@christopherthielen any chance of merging this PR?

**Comment by christopherthielen** [comment]
Released as 2.1.0

**Comment by Arlanthir** [comment]
Thanks!

**Pull request merged**
